export const tokens = {
  colors: {
    pageBackground: '#f3f7fb',
    shellBackground: 'rgba(255, 255, 255, 0.88)',
    surface: '#ffffff',
    surfaceMuted: '#f8fbff',
    surfaceAccent: '#eff6ff',
    border: '#dbe4f0',
    borderStrong: '#bfdbfe',
    text: '#0f172a',
    textMuted: '#475569',
    textSubtle: '#64748b',
    primary: '#2563eb',
    primaryStrong: '#1d4ed8',
    primarySoft: '#dbeafe',
    success: '#047857',
    danger: '#b91c1c',
    warningSurface: '#fff7ed',
    warningBorder: '#fed7aa',
    warningText: '#92400e',
    darkSurface: '#0f172a',
    darkText: '#cbd5e1',
  },
  shadows: {
    shell: '0 18px 40px rgba(15, 23, 42, 0.08)',
    primary: '0 12px 24px rgba(37, 99, 235, 0.2)',
    soft: '0 10px 30px rgba(15, 23, 42, 0.06)',
  },
  radii: {
    pill: '999px',
    lg: '24px',
    md: '20px',
    sm: '16px',
    xs: '12px',
  },
  spacing: {
    pageX: '20px',
    pageY: '32px',
    sectionGap: '24px',
    cardPadding: '24px',
    shellWidth: '1200px',
    contentWidth: '1120px',
    formWidth: '520px',
  },
};

export const shellStyles = {
  appShell: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    background:
      'radial-gradient(circle at top, rgba(219, 234, 254, 0.7) 0%, rgba(243, 247, 251, 0.95) 28%, #f8fbff 100%)',
    color: tokens.colors.text,
  },
  shellFrame: {
    width: '100%',
    maxWidth: tokens.spacing.shellWidth,
    margin: '0 auto',
    padding: `0 ${tokens.spacing.pageX} ${tokens.spacing.pageY}`,
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacing.sectionGap,
    flex: 1,
  },
  pageSection: {
    width: '100%',
    maxWidth: tokens.spacing.contentWidth,
    margin: '0 auto',
    boxSizing: 'border-box',
  },
  pageStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: tokens.spacing.sectionGap,
  },
  sectionCard: {
    backgroundColor: tokens.colors.surface,
    border: `1px solid ${tokens.colors.border}`,
    borderRadius: tokens.radii.lg,
    boxShadow: tokens.shadows.shell,
    padding: '32px',
    boxSizing: 'border-box',
  },
  mutedCard: {
    backgroundColor: tokens.colors.surfaceMuted,
    border: `1px solid ${tokens.colors.border}`,
    borderRadius: tokens.radii.md,
    padding: tokens.spacing.cardPadding,
    boxSizing: 'border-box',
  },
  eyebrow: {
    alignSelf: 'flex-start',
    backgroundColor: tokens.colors.primarySoft,
    color: tokens.colors.primaryStrong,
    borderRadius: tokens.radii.pill,
    padding: '8px 14px',
    fontSize: '0.85rem',
    fontWeight: 700,
    letterSpacing: '0.02em',
  },
  primaryButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '44px',
    padding: '12px 20px',
    borderRadius: tokens.radii.pill,
    backgroundColor: tokens.colors.primary,
    color: '#ffffff',
    textDecoration: 'none',
    fontWeight: 700,
    border: `1px solid ${tokens.colors.primary}`,
    boxShadow: tokens.shadows.primary,
    boxSizing: 'border-box',
  },
  secondaryButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '44px',
    padding: '12px 20px',
    borderRadius: tokens.radii.pill,
    backgroundColor: tokens.colors.surface,
    color: tokens.colors.text,
    textDecoration: 'none',
    fontWeight: 700,
    border: `1px solid ${tokens.colors.border}`,
    boxSizing: 'border-box',
  },
};

/**
 * Returns shared layout wrappers and visual tokens for the recruitment shell.
 */
export function getPageShellStyles({ centered = false, narrow = false } = {}) {
  return {
    page: {
      width: '100%',
      maxWidth: narrow ? tokens.spacing.formWidth : tokens.spacing.contentWidth,
      margin: '0 auto',
      display: 'flex',
      flexDirection: 'column',
      gap: tokens.spacing.sectionGap,
      justifyContent: centered ? 'center' : 'flex-start',
      boxSizing: 'border-box',
    },
    card: {
      ...shellStyles.sectionCard,
      width: '100%',
    },
  };
}
